<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0-windows</TargetFrameworks>
    <NoWarn>1591,1573</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="data\*.locale.bson" Exclude="bin\**;obj\**;**\*.xproj;packages\**;@(EmbeddedResource)" />
  </ItemGroup>
</Project>