<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

	<PropertyGroup>
		<BaseOutputPath>bin</BaseOutputPath>
		 <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		 <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		 <OutputPath>$(BaseOutputPath)</OutputPath>
	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="call postbuild.bat" />
	</Target>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
  </ItemGroup>

</Project>
