<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Wff.Controls">
      <HintPath>..\..\..\Dlls\Wff.Controls.dll</HintPath>
    </Reference>
    <Reference Include="Wff.VtkWpf">
      <HintPath>..\..\..\Dlls\Wff.VtkWpf.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
